code

equ	trap_Error								-1
equ	trap_Print								-2
equ	trap_Milliseconds						-3
equ	trap_Cvar_Set							-4
equ	trap_Cvar_VariableValue					-5
equ	trap_Cvar_VariableStringBuffer			-6
equ	trap_Cvar_SetValue						-7
equ	trap_Cvar_Reset							-8
equ	trap_Cvar_Create						-9
equ	trap_Cvar_InfoStringBuffer				-10
equ	trap_Argc								-11
equ	trap_Argv								-12
equ	trap_Cmd_ExecuteText					-13
equ	trap_FS_FOpenFile						-14
equ	trap_FS_Read							-15
equ	trap_FS_Seek							-16
equ	trap_FS_Write							-17
equ	trap_FS_FCloseFile						-18
equ	trap_FS_GetFileList						-19
equ trap_FS_Delete							-20
equ	trap_R_RegisterModel					-21
equ	trap_R_RegisterSkin						-22
equ	trap_R_RegisterShaderNoMip				-23
equ	trap_R_ClearScene						-24
equ	trap_R_AddRefEntityToScene				-25
equ	trap_R_AddPolyToScene					-26
equ trap_R_AddPolysToScene					-27
equ	trap_R_AddLightToScene					-28
equ trap_R_AddCoronaToScene					-29
equ	trap_R_RenderScene						-30
equ	trap_R_SetColor							-31
equ	trap_R_DrawStretchPic					-32
equ	trap_UpdateScreen						-33
equ	trap_CM_LerpTag							-34
equ	trap_CM_LoadModel						-35
equ	trap_S_RegisterSound					-36
equ	trap_S_StartLocalSound					-37
equ	trap_S_FadeBackgroundTrack				-38
equ	trap_S_FadeAllSound						-39
equ	trap_Key_KeynumToStringBuf				-40
equ	trap_Key_GetBindingBuf					-41
equ	trap_Key_SetBinding						-42
equ	trap_Key_IsDown							-43
equ	trap_Key_GetOverstrikeMode				-44
equ	trap_Key_SetOverstrikeMode				-45
equ	trap_Key_ClearStates					-46
equ	trap_Key_GetCatcher						-47
equ	trap_Key_SetCatcher						-48        
equ	trap_GetClipboardData					-49
equ	trap_GetGlconfig						-50
equ	trap_GetClientState						-51
equ	trap_GetConfigString					-52
equ	trap_LAN_GetLocalServerCount			-53
equ	trap_LAN_GetLocalServerAddressString	-54
equ	trap_LAN_GetGlobalServerCount			-55
equ	trap_LAN_GetGlobalServerAddressString	-56
equ	trap_LAN_GetPingQueueCount				-57
equ	trap_LAN_ClearPing						-58
equ	trap_LAN_GetPing						-59
equ	trap_LAN_GetPingInfo					-60
equ	trap_Cvar_Register						-61
equ trap_Cvar_Update						-62
equ trap_MemoryRemaining					-63
equ	trap_GetCDKey							-64
equ	trap_SetCDKey							-65
equ trap_R_RegisterFont						-66
equ trap_R_ModelBounds						-67
equ trap_PC_AddGlobalDefine					-68
equ	trap_PC_LoadSource						-69
equ trap_PC_FreeSource						-70
equ trap_PC_ReadToken						-71
equ trap_PC_SourceFileAndLine				-72
equ trap_S_StopBackgroundTrack				-73
equ trap_S_StartBackgroundTrack				-74
equ trap_RealTime							-75
equ trap_LAN_GetServerCount					-76
equ trap_LAN_GetServerAddressString			-77
equ trap_LAN_GetServerInfo					-78
equ trap_LAN_MarkServerVisible 				-79
equ trap_LAN_UpdateVisiblePings				-80
equ trap_LAN_ResetPings						-81
equ trap_LAN_LoadCachedServers				-82
equ trap_LAN_SaveCachedServers				-83
equ trap_LAN_AddServer						-84
equ trap_LAN_RemoveServer	 				-85
equ trap_CIN_PlayCinematic					-86
equ trap_CIN_StopCinematic					-87
equ trap_CIN_RunCinematic 					-88
equ trap_CIN_DrawCinematic					-89
equ trap_CIN_SetExtents						-90
equ trap_R_RemapShader						-91
equ trap_VerifyCDKey						-92
equ trap_LAN_ServerStatus					-93
equ trap_LAN_GetServerPing					-94
equ trap_LAN_ServerIsVisible				-95
equ trap_LAN_CompareServers					-96
equ trap_GetLimboString						-97

equ	memset						-101
equ	memcpy						-102
equ	strncpy						-103
equ	sin							-104
equ	cos							-105
equ	atan2						-106
equ	sqrt						-107
equ floor						-108
equ	ceil						-109

; New in iortcw
equ trap_Alloc					-901

