code

equ	trap_Error								-1
equ	trap_Print								-2
equ	trap_Milliseconds						-3
equ	trap_Cvar_Set							-4
equ	trap_Cvar_VariableValue					-5
equ	trap_Cvar_VariableStringBuffer			-6
equ	trap_Cvar_SetValue						-7
equ	trap_Cvar_Reset							-8
equ	trap_Cvar_Create						-9
equ	trap_Cvar_InfoStringBuffer				-10
equ	trap_Argc								-11
equ	trap_Argv								-12
equ	trap_Cmd_ExecuteText					-13
equ	trap_FS_FOpenFile						-14
equ	trap_FS_Read							-15
equ	trap_FS_Write							-16
equ	trap_FS_FCloseFile						-17
equ	trap_FS_GetFileList						-18
equ trap_FS_Delete							-19
equ	trap_R_RegisterModel					-20
equ	trap_R_RegisterSkin						-21
equ	trap_R_RegisterShaderNoMip				-22
equ	trap_R_ClearScene						-23
equ	trap_R_AddRefEntityToScene				-24
equ	trap_R_AddPolyToScene					-25
equ trap_R_AddPolysToScene					-26
equ	trap_R_AddLightToScene					-27
equ trap_R_AddCoronaToScene					-28
equ	trap_R_RenderScene						-29
equ	trap_R_SetColor							-30
equ	trap_R_DrawStretchPic					-31
equ	trap_UpdateScreen						-32
equ	trap_CM_LerpTag							-33
equ	trap_CM_LoadModel						-34
equ	trap_S_RegisterSound					-35
equ	trap_S_StartLocalSound					-36
equ	trap_Key_KeynumToStringBuf				-37
equ	trap_Key_GetBindingBuf					-38
equ	trap_Key_SetBinding						-39
equ	trap_Key_IsDown							-40
equ	trap_Key_GetOverstrikeMode				-41
equ	trap_Key_SetOverstrikeMode				-42
equ	trap_Key_ClearStates					-43
equ	trap_Key_GetCatcher						-44
equ	trap_Key_SetCatcher						-45        
equ	trap_GetClipboardData					-46
equ	trap_GetGlconfig						-47
equ	trap_GetClientState						-48
equ	trap_GetConfigString					-49
equ	trap_LAN_GetLocalServerCount			-50
equ	trap_LAN_GetLocalServerAddressString	-51
equ	trap_LAN_GetGlobalServerCount			-52
equ	trap_LAN_GetGlobalServerAddressString	-53
equ	trap_LAN_GetPingQueueCount				-54
equ	trap_LAN_ClearPing						-55
equ	trap_LAN_GetPing						-56
equ	trap_LAN_GetPingInfo					-57
equ	trap_Cvar_Register						-58
equ trap_Cvar_Update						-59
equ trap_MemoryRemaining					-60
equ	trap_GetCDKey							-61
equ	trap_SetCDKey							-62
equ trap_R_RegisterFont						-63
equ trap_R_ModelBounds						-64
equ trap_PC_AddGlobalDefine					-65
equ	trap_PC_LoadSource						-66
equ trap_PC_FreeSource						-67
equ trap_PC_ReadToken						-68
equ trap_PC_SourceFileAndLine				-69
equ trap_S_StopBackgroundTrack				-70
equ trap_S_StartBackgroundTrack				-71
equ trap_RealTime							-72
equ trap_LAN_GetServerCount					-73
equ trap_LAN_GetServerAddressString			-74
equ trap_LAN_GetServerInfo					-75
equ trap_LAN_MarkServerVisible 				-76
equ trap_LAN_UpdateVisiblePings				-77
equ trap_LAN_ResetPings						-78
equ trap_LAN_LoadCachedServers				-79
equ trap_LAN_SaveCachedServers				-80
equ trap_LAN_AddServer						-81
equ trap_LAN_RemoveServer	 				-82
equ trap_CIN_PlayCinematic					-83
equ trap_CIN_StopCinematic					-84
equ trap_CIN_RunCinematic 					-85
equ trap_CIN_DrawCinematic					-86
equ trap_CIN_SetExtents						-87
equ trap_R_RemapShader						-88
equ trap_VerifyCDKey						-89
equ trap_LAN_ServerStatus					-90
equ trap_LAN_GetServerPing					-91
equ trap_LAN_ServerIsVisible				-92
equ trap_LAN_CompareServers					-93
equ trap_GetLimboString						-94
equ trap_SetPbClStatus						-95
equ trap_CheckAutoUpdate					-96
equ trap_GetAutoUpdate						-97
equ trap_TranslateString					-98
equ trap_openURL							-99
equ trap_SetPbSvStatus						-100

equ	memset						-101
equ	memcpy						-102
equ	strncpy						-103
equ	sin							-104
equ	cos							-105
equ	atan2						-106
equ	sqrt						-107
equ floor						-108
equ	ceil						-109

